// contentpilot/apps/web/app/page.tsx

export default function Home() {
  return (
    <main className="min-h-screen bg-vapor-gray text-ink p-8">
      <h1 className="text-4xl font-bold text-sky-navy">Welcome to ContentPilot</h1>
      <p className="mt-4 text-lg max-w-xl">
        Let your audience vote with their wallet to choose what you create next. This is the launchpad.
      </p>
    </main>
  );
}

// contentpilot/turbo.json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "dev": {
      "cache": false
    },
    "lint": {},
    "format": {}
  }
}

// contentpilot/package.json
{
  "name": "contentpilot",
  "private": true,
  "workspaces": ["apps/*", "packages/*"],
  "scripts": {
    "dev": "turbo run dev",
    "build": "turbo run build",
    "lint": "turbo run lint",
    "format": "turbo run format"
  },
  "devDependencies": {
    "turbo": "^1.11.3"
  }
}

// contentpilot/convex/schema.ts
import { defineSchema, v } from 'convex/schema';

export default defineSchema({
  ideas: {
    title: v.string(),
    description: v.string(),
    creatorId: v.string(),
    pledgedAmount: v.number(),
    goal: v.number(),
    createdAt: v.number(),
  },
});

// contentpilot/apps/web/convex/_generated/client.ts
// This will be generated by Convex CLI

// contentpilot/apps/web/convex/config.json
{
  "project": "contentpilot",
  "apiUrl": "https://your-convex-deployment.convex.cloud"
}

// contentpilot/packages/ui/index.tsx
export const Button = ({ children }: { children: React.ReactNode }) => (
  <button className="px-4 py-2 rounded-xl bg-lilac-boost text-white font-medium hover:opacity-90">
    {children}
  </button>
);

// contentpilot/packages/utils/index.ts
export const formatCurrency = (amount: number) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);

// contentpilot/apps/web/tailwind.config.ts
import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', '../../packages/ui/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'sky-navy': '#1A274C',
        'lilac-boost': '#AA80FF',
        'vapor-gray': '#F8F9FB',
        'ink': '#141414',
        'mint-glow': '#A3F7BF',
      },
    },
  },
  plugins: [],
};

export default config;
